### ISSUE TITLE
Docker environment for development

### ISSUE THREAD

**Issue by tomaszbawor** [elementum-games/shinobi-chronicles#102]
Hey, 

Have you considered dockerizing development environment? I would like to contribute (And could take care of setting that up) . Also lot of people are rn using docker on their local machines and that would simplify setting up project?

**Comment by levimeahan** [comment]
Hmm yeah that could be nice - I haven't done any setup work with docker (just used containers), what would be involved?

**Comment by tomaszbawor** [comment]
I have made several things, I want to prepare docker-compose file with setup to start whole application. Basicly after pulling out the project you will be able to run only 'docker-compose up' and it would prepare containers with database (with version as on prod), and container with application exposing ports so no further configuration would be needed.
