### ISSUE TITLE
Add auto refresh in travel page ($300)

### ISSUE THREAD

**Issue by Rhaegarrr** [elementum-games/shinobi-chronicles#107]
Add auto refresh in combat and travel page

**Comment by levimeahan** [comment]
Bounty: $300

**Acceptance Criteria**
TODO: Add example structure for dynamic interfaces, to clarify how to approach this
- Interface ported to ReactJS
- Back-end API endpoint that returns JSON created for moving and viewing nearby users
- Traveling should use the endpoint
- The nearby player list should automatically refresh using the endpoint to fetch the latest list of available users, every 500ms
