### ISSUE TITLE
Forbidden seal upgrade - keep partial aura time

### ISSUE THREAD

**Issue by HitoriWoB** [elementum-games/shinobi-chronicles#108]
When upgrading from Twin Serpant to Foir Dragon, allow 20% to 25% of time remaining on Twin Serp to transfer over. Display a purchase confirmation page.

Prevent downgrading, or allow full transfer of time to Twin Dragons, with warning on confirmation that upgrading will result in loss of time. Perhaps give 20 to 25% more time (could be useful for capped users that can't benefit from training with current aura features and just need skcial/journal benefits).

*Alternative*

Issue confirmation page that changing seals will result in loss of current aura time.

**Comment by levimeahan** [comment]
Sounds good to me. We can do 25% time transfer on upgrade
