### ISSUE TITLE
[WIP] Support Request System

### ISSUE THREAD

**Issue by HitoriWoB** [elementum-games/shinobi-chronicles#140]
Add support request system - similar to how WoB's work.

**Comment by HitoriWoB** [comment]
@Algharna 
Any chance of getting an icon made for the top menu for support link?

**Comment by AlvinValens** [comment]
https://i.imgur.com/QBrnGhP.png
https://i.imgur.com/g65oqcG.png

**Comment by HitoriWoB** [comment]
![image](https://user-images.githubusercontent.com/24821372/137786906-7d267f6c-b8fa-46b3-aeda-09f8db229c50.png)
Staff area coming along.

**Comment by HitoriWoB** [comment]
Staff assignment and removal now functional.
User ticket closing functional - but must provide a response to close the ticket, so that if it gets reviewed there's a reason for closing.
-Technical note: User closed tickets `open` is set to -1 and staff closed tickets are set to 0
User will be notified via PM when their support is updated - assigned staff member notification is in-progess --- not sure whether to do via PM or have it be a regular notification (like active reports, new pms, etc).
