### ISSUE TITLE
Investigate heal multipliers

### ISSUE THREAD

**Issue by levimeahan** [elementum-games/shinobi-chronicles#15]
> Heal:194 * 0.052 -> 10.09 per turn
> 
> Okay, so this was 
>
> Heal:100 * 0.062 -> 6.2 per turn
> 
> When I obtained the BL. Since then, the multiplier thingy has
been slowly decreasing. That's intended?

**Comment by MiteyDrill** [comment]
Has this been fixed?

**Comment by MiteyDrill** [comment]
Just a theory but I think the totalskill multiplier is negatively affecting the heal boost over time, but I think it's intended for some skills. Not sure if it is for heal...
