### ISSUE TITLE
Add battle logs that can be reviewed later

### ISSUE THREAD

**Issue by levimeahan** [elementum-games/shinobi-chronicles#152]
E.g. last 20 battles

- Link to "Battle Logs" on profile
- Only for Forbidden Seal users (lower tier is fine)

**Comment by aumu1031** [comment]
I have this set up as follows.
- "Battle History" tab added to profile
- Only visible if user has seal and is Genin rank or higher
- Displays a limit of last 20 user battles in table with view link
- Displays selected battle log; same page in second table ordered by turn
- Can only view battle if it is within the 20 most recent

Questions:
Are there any other requirements?
"Battle History" tab makes the profile nav cramped. Should send Money/AK could be combined for space?

![image](https://user-images.githubusercontent.com/129538454/236113569-876b303d-5927-42c8-a1fa-f3c109eadbd7.png)

**Comment by aumu1031** [comment]
Per suggestion above combining Money/AK pages:
![image](https://user-images.githubusercontent.com/129538454/236118900-f7f644f8-ed39-4ac3-af0c-8a6373bfd459.png)
