### ISSUE TITLE
AK Exchange

### ISSUE THREAD

**Issue by unownram** [elementum-games/shinobi-chronicles#166]
add an extra column that lets us know how much it costs per AK when someone sells more than one at once. Maths is hard and I an very lazy. :(

**Comment by ViscaBarre** [comment]
Alternatively: change it so the default displayed order is from lowest to highest, taking the individual pricing into account. FFXIV'S market board does this.

![image](https://user-images.githubusercontent.com/91370970/137640675-e18ce633-4246-4b28-bd67-2e80e7a41794.png)

**Comment by levimeahan** [comment]
This is now done thanks to @HitoriWoB !
