### ISSUE TITLE
Organizing jutsu page

### ISSUE THREAD

**Issue by Blade2029** [elementum-games/shinobi-chronicles#174]
Organizing jutsu page or give options to organize them by
-Elements
-Rank
-offense

Also as a side note, displaying levels at the end can help as well

**Comment by ViscaBarre** [comment]
Jutsu page is one of the many pages I intend to re-design for new Geisha layout. Some emergency tweaks could be done beforehand though, as I will take a long while.

By offence, do you mean offence type (tai/nin/gen) or the power?

**Comment by Blade2029** [comment]
I was thinking more like rank>offense>element...like a drop down menu after clicking rank,then displaying by offense and elements, or elements can be displayed on the right side of jutsu along with level...

Chunnin
Genjutsu
metal vigor          fire               100

i understand that elements dont exist for all jutsus now...

i hope explained it right
