### ISSUE TITLE
Clearing handsigns

### ISSUE THREAD

**Issue by unownram** [elementum-games/shinobi-chronicles#187]
Sometimes I change my mind about which jutsu to use after I entered the handsigns. Instead of having to reclick/touch them all, would be nice to have a clear button.

**Comment by HitoriWoB** [comment]
@aumu1031 
Do you know if this got resolved with some of the battle changes you did?

**Comment by aumu1031** [comment]
> @aumu1031 Do you know if this got resolved with some of the battle changes you did?

Yep can be closed.
