### ISSUE TITLE
Nerf Speed clash stats to avoid damage 50% -> 25% in combat

### ISSUE THREAD

**Issue by Rhaegarrr** [elementum-games/shinobi-chronicles#199]
**Nerf Speed clash stats to avoid damage 50% -> 25% in combat.**

**Comment by HitoriWoB** [comment]
@levimeahan Is this something you'd be interested in considering?

**Comment by levimeahan** [comment]
Speed has now been updated and the damage reduction cap is reduced. This hopefully should achieve the desired affects here
