### ISSUE TITLE
Effects displayed in combat page

### ISSUE THREAD

**Issue by Blade2029** [elementum-games/shinobi-chronicles#205]
We have lot of effects/tags, as we add more of it, why not add a system that displays the effects that are active in a particular round

for example i use offense buff round 1 and placeholder nerf round 2--->round 3 both will be active, why not display them as a drop down menu in the battle page along with jutsu descriptions and damage or in some other way along with round number...

just a QOL update, that will help many players :)

**Comment by ViscaBarre** [comment]
New combat page design has a dedicated place to display ongoing buffs/debuffs on players. It was one of the most significant QoL features I wanted to add to help make battles easier to understand. :)

**Comment by Blade2029** [comment]
> New combat page design has a dedicated place to display ongoing buffs/debuffs on players. It was one of the most significant QoL features I wanted to add to help make battles easier to understand. :)

ah really great :) 👍
