### ISSUE TITLE
Stat and Exp bug after resetting

### ISSUE THREAD

**Issue by Justeen208** [elementum-games/shinobi-chronicles#229]
For thr account named Tetsuishi, I was attempting to reroll until I get a better BL, on the latest attempt, before resetting back to lvl1 AS, I started the extended Genin Training, so when the training finishes, even the account is an AS it will still get the stat gains for the Genin level, there was no problem when I did this on a previous run, but in the latest one, I got the stat points just fine but it seems I didn’t get all the exp, to my understading, your total stat is equal to your exp mutiplied by 10, but that doesnt seem to be the case on the current state of the account

**Comment by jayantamadhav** [comment]
I would also like to add here that after resetting, the mission stats doesn't get reset

**Comment by levimeahan** [comment]
This should be resolved now, we've updated stat gains to fix your exp each time
