### ISSUE TITLE
Ramen Shop

### ISSUE THREAD

**Issue by ReiChan5446** [elementum-games/shinobi-chronicles#263]
Ramen Shop looks very sad. I would suggest adding a pic to make it more attractive. I am on an art spree,  so I made one.

Hopefully, It can be added :3

![ramen](https://user-images.githubusercontent.com/92738734/218234931-a2ec45ad-2088-41d6-95a4-dd4514c6cdad.png)

Here an example of how it would look like in-game: 

![display-ramen-shop](https://user-images.githubusercontent.com/92738734/218234971-ffca858f-17f2-4a53-8828-1aa9bd80683d.png)

**Comment by levimeahan** [comment]
Awesome, done!
![image](https://user-images.githubusercontent.com/1691258/234473791-7dd19fd5-3224-4a13-b35d-3fdab5918dbb.png)

**Comment by levimeahan** [comment]
What is your SC username?

**Comment by levimeahan** [comment]
AK sent!
