### ISSUE TITLE
Expand battle logs functionality

### ISSUE THREAD

**Issue by aumu1031** [elementum-games/shinobi-chronicles#297]
Related to #152

- Track health of players
- Display battle UI (health, portraits, etc.)
- Track jutsu names / effects? 
- Changes for combat update?

**Comment by aumu1031** [comment]
Expand limit for history based on seal (20->30)?

**Comment by aumu1031** [comment]
Move Battle History into its own tab within View Battles

**Comment by HitoriWoB** [comment]
@aumu1031 
I know you've been putting a lot of work into this feature. Has any of this been incorporated with the most recent logs update?

**Comment by aumu1031** [comment]
Yep this can be closed.

**Comment by aumu1031** [comment]
> @aumu1031 I know you've been putting a lot of work into this feature. Has any of this been incorporated with the most recent logs update?

Yep can be closed.
