### ISSUE TITLE
AI combat texts list their name twice

### ISSUE THREAD

**Issue by levimeahan** [elementum-games/shinobi-chronicles#36]
> Furious Tiger Furious Tiger eyes glimmer as they move at incredible speed, leaving a blue streak in their haste. The blue streak passes though Lsmjudoka causing them to hunch over in sever pain, bleeding where the streak had passed.

Currently their name is automatically preprended to the combat text, but also there's an `[opponent]` tag in the combat text that gets substituted for their name. We should leave flexibility in the hands of the admin panel and remove the code that automatically prepends their name to the combat text.

**Comment by ColinLubout** [comment]
I think this issue has been resolved as I can't seem to reproduce it.
