### ISSUE TITLE
QoL: Add group chat / ability to send Same Message to More Than 1 User

### ISSUE THREAD

**Issue by coolingoreo** [elementum-games/shinobi-chronicles#47]
Example:

http://prntscr.com/1sqb9f5

**Comment by levimeahan** [comment]
Hmm what would you use this for, like group chat?

**Comment by coolingoreo** [comment]
just sending messages to multiple ppl of the same subject when wanted to.

e.g.:  mue sending DnD info to all of us at once instead of one by one.
