### ISSUE TITLE
Teacher/Student gameplay

### ISSUE THREAD

**Issue by MiteyDrill** [elementum-games/shinobi-chronicles#78]
something that involves sensei/student type relationship in-game would be kinda cool to have and give players something to bond about

**Comment by coolingoreo** [comment]
maybe increased gains % from training ,or learning jutsus faster, or earning extra income from mission, or ramen shop/items cost less , extra 10 regen etc

**Comment by ViscaBarre** [comment]
- Are there requirements to become a sensei?
- How would a player become a sensei?
- Would sensei have their own area of specialization so they'd train only certain kinds of students or any will do? With these I'm thinking of a way to display/promote themselves.
- Any progression mechanics for sensei itself? Is seeing students graduate enough?

- How will a student find a sensei for themselves?
- How will a sensei find students?
- How many students would a sensei have at a time?
- Are there activities these students can do either with each other or with their sensei? Exclusive to sensei-student.

Rando-idea: Swap out Village Menu, turn it into Academy Menu. Add sensei listing.

**Comment by ViscaBarre** [comment]
**Yasutake** has given some thoughts on this on Discord. I'll post on his behalf:

**Are there requirements to become a sensei?**

- An active player of the game, Chuunin (1 student) Jounin (3 stuents)

**How would a player become a sensei?**

- A player would become a Sensei by either requesting to be one directly at the village center, and is given a quota of students to take on, probably a droplist of available genin.

**Would sensei have their own area of specialization so they'd train only certain kinds of students or any will do? With these I'm thinking of a way to display/promote themselves.**

- They can train all students, however if they specialize in a specific area then the student they take on, who also specializes there, has a training boost. 

**Any progression mechanics for sensei itself? Is seeing students graduate enough?**

- Seeing students graduate, become clan leaders, maybe Kage, gain PVP kills, become Bounty hunters, Established medical Nin, or even taking on students themselves

**How will a student find a sensei for themselves?**

- A student would most likely have to approach via mail and ask, with confirmation their active.

**How will a sensei find students?**

- Checking the village registry for active genin (and from the droplist mentioned earlier) 

**How many students would a sensei have at a time?**

- 1 (chuunin) 3( Jounin)

**Are there activities these students can do either with each other or with their sensei? Exclusive to sensei-student.**

- Yes, a 4 way spar with the two students and their sensei, 
- A 3 way free for all against eachother, group training which enhances their abilities faster, 
- Group missions to be carried out together, they're dynamic, so a C rank can change to a B/A rank for the thrill of uncertainty.

**Comment by MiteyDrill** [comment]
This all sounds pretty good, i'm starting work on a sensei system on my local machine. Not sure if it'll ever be implemented but i'll try to whip something up - right now i'm just trying to set it up so a user can be set up as a teacher or a student and how the information will be stored and grabbed, etc. I'm also thinking of setting up so there's a student registry and teacher registry but still thinking about that. Its pretty basic tho and not so clean. So i'm a little hesitant about it ever being used in production but I think of it as good practice.

For boosts i'm thinking of giving students a 15% training boost -> with teachers starting with a 1.01x multiplier boost so 1% of gains and as students earn skill points the sensei equivalently earns 1 teaching skill point for every 1 skill point a student learns. Right now I just want to see if I can get the system running and implemented without clogging up any of the other code already set up. For teachers its not very useful but with time maybe we can add other boosts or more student-teacher interactivity.

Right now i'm setting up a Sensei_Manager class that'll handle the DB interaction as well as allocate or update any information regarding sensei or student in the User Class. If I can get that working then i'll move on to figuring out just how the registering students or claiming teachers process will even work. 

If I can get a simple sensei system set up we can work on any needed changes for the online dev build and then work on improvements and extra bits in time with Lsm's approval. Maybe somebody else can take over too since i'm not very experienced and can't work on it as much as the average person.
