### ISSUE TITLE
Add daily task (X number of AI fights) with money reward

### ISSUE THREAD

**Issue by levimeahan** [elementum-games/shinobi-chronicles#9]
At a minimum this is a tracked number with # of fights completed and a timestamp of the last reset. 

We check this the end of every fight, if it's been > 24 hours since last reset and user hasn't completed, we reset it. If user hits the quote within 24 hours, we reward a chunk of extra money and stop counting for that day.

**Comment by MiteyDrill** [comment]
If nobody is working on this currently, I can maybe try setting this up tomorrow. Doesn't seem too bad, could save the time-stamp as a long int using a Date class if PHP has one. If php doesn't have a date class I might run into some trouble.

**Comment by SatoGojo** [comment]
Would it be possible to add this in for PVP/Missions as well?

**Comment by levimeahan** [comment]
> 
> 
> Would it be possible to add this in for PVP/Missions as well?

I like that idea, a daily PvP task and daily PvE task?
